server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://192.168.123.102:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.123.102
      port: 6379
      password: redis
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

jwt:
  token:
    sign-key: 123456