server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://192.168.123.102:3306/user?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    username: guest
    password: rabbit
    host: 192.168.123.102
    port: 5672
    #    listener:
    #      simple:
    #        acknowledge-mode: manual
    #      direct:
    #        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated


  data:
    redis:
      host: 192.168.123.102
      port: 6379
      password: redis
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

jwt:
  token:
    sign-key: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  app_id: 2021000121697719
  private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCGs7WsuN9cvtAq+q6lw0HvUxCmah7OYVIqK2BoaKP86f6tycu1Ko7xY8CuLCQG0yo9yi8M6p1KwhH4DSbt8v5G0nWYgMjR/HfaflD31Rh6RvQRZyr3IbS4HR2EI3C/yg1W6pibP6hapZcQL0An1/hkZJzdWNJ/LP23u6PbxeUhLhmcKfCP9cTOkKFYrbW1/OzdX+uXgwXqCj9isQBnn2bHu/UI3N4McDZhJkThkcJIG/IZk1ZSlzfmNctVjC1MG5+x1vm4FdiGt1qyRku/1GO8T5Jd3BW/6Mrb++lLC5fls5vDV8RZrsZgnsHuuc6ETiBgMCLvmvaW5tgE38ncEgrRAgMBAAECggEAGIdVB9TKZ7sfcRQhBXJe6VO47nTYk0BJlAA+GAUmB4IcrEzY2W6chPxjM9Q54zxErufIVZPLfLeGSiMq+Z2MDB166IBbEVHmCVWDLP4S7QFKpHii7Emo/PXgUBWcDHCgqTki/PJEl+0bawkPp7G+O5nOrsfj3OC2euSiW/zXUokseLkgfXTTz1xeVz7F5o+i1NSMTIkpurUwAlQSKvjmO31Z1JzUvoP5ga8MV1RDQoJ4WKYbqs0rA4YZPjnbqlwh6tLdJ9KPOZu4zGDMDVWXnRfhjyL2HAxzAmSNBwcST5SygwmtlyLyQzSryXabPJyaV8t4Jn+m1jXDo7S022DQAQKBgQDPeTV9WQ8ZCxQd7M3DF+a3vzbBO596/luzvtjl+jPxgOSNs2S/w0JlIigkI5aR3OLa/eetA9t5wMKx+DkUyKiOW65hDQCXuG+E3lfUlwvqvb4sjo8TRYXoA5wqLyMLN0ebPwobW4kaLEuNQlVWWIBtbg1Pk1TiLDS4EgbtYtlTgQKBgQCmNTJ2E5Bd2TD33g7F12ojWJuFCCeJouY3u5xJTDCy1WpyD3Ab+65wYRaf8LjZWlM+FSO9MeKH3A/vRSWUEYEiQzjFZqjQ04mNqdpKwJSKRPtlZt1ZrW2sxRPHRQHKXH/HNF8moxikpngJrp1t2S0uBmPeAEB5SKk/R2aZdTIfUQKBgHPiogv3uMUmOQBWCsBUE1zDA1R/dx7+AD6v9PrP/D+C3SaA819hMy7GG2HENxAWLuhfNg6fvvGMx7MckNWZFv0dHJO87X3RWQkAIFLwY4mknhrJLgV3qcnkak/tsEdNg0OlvIF3aWcjIrguOvhVyrZU6D5wbtM+GdxOxWvG8NkBAoGBAIPamfCQLqw0/CL3N7L95Iar6ZyMzojjAU3feOmxFsUYh3x7AM5CSK2AaCl0F8DeZkFPFe4mn/Z1vvJrYZdol5At0eDQQ0Z/OpV21OUOiAh1FxbnltxouCQiqEEiXnxCC2BmDMIjCw67vWi47M1TSANGMH3Sp1NQMGwx4ZQGJEAxAoGBALg53fydVNfwJ96aUcsjDTN+FgaEZQGGh64I/Yyk/qSz7B1ABK02N6EfWQMDZrQxUD8XtquJOwvpqgIL5CDtNTaJ5gCFn1vMeFB8zRV4jgSn3r01yMeTxDh0blaIMcRbmBHs8+40AThVd48mpt5uGgvp9xZJOraGH+WtTSefaLBZ
  pub_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmQCrB4aGcm28zFf3DV0cqaSKJzGm8i05F0klUhHqFXtJoZ2/JKZ1FtCcJbZMDr5jVCzbiEnEE47rTP+0WYDqqZz3DiOQILr/gyMWZFkjR2V0RdoeKvIi3W7bDTpEkkCsOSEZtZA3SRnEvdj1rfCGLPr74L23civyxnAawFLFm1ObVUWyatZ5rLswfmg2nK1rOSF5Cx+3LeJydXDkk7oGaum+SJe0k4Z34AijMUjLZMLBezDvNMeHfe/Cn2K+rChFCpOc3kv5Jfz7HES30hH4aweLiCFgd9EYFOVcZiz1MKqc2vt22XUEvbsohlOJHU9HCy4aj+qVDT91R3bzODBtMwIDAQAB
  sign_type: RSA2
  gateway: https://openapi.alipaydev.com/gateway.do
