server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://192.168.123.102:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

